<form id="<?=$this->form->getId()?>" name="<?=$this->form->getName()?>" enctype="<?=$this->form->getEnctype()?>" action="<?=$this->form->getAction()?>" method="<?=$this->form->getMethod()?>">
	<legend>Register for an account</legend>
	<table>
<?if ($this->__isset('error') && count($this->error)) {
if (in_array('dataInvalid', $this->error)) $error_message = 'Credentials You used is not valid.';
if (in_array('passwordsNotMatch', $this->error)) $error_message = 'Passwords didn\'t match	.';
?>
		<tr>
			<td><p class="alert alert-danger form-alert"><?=$error_message?></p></td>
		</tr>
<? } ?>
		<tr>
			<td><div class="form-group"><?=$this->form->nickname?></div></td>
		</tr>
		<tr>
			<td><div class="form-group"><?=$this->form->email?></div></td>
		</tr>
		<tr>
			<td><div class="form-group"><?=$this->form->password?></div></td>
		</tr>
		<tr>
			<td><div class="form-group"><?=$this->form->password_confirm?></div></td>
		</tr>
<?if ($this->form->ReCaptcha) {?>
		<tr>
			<td><div class="form-group"><?=$this->form->ReCaptcha?></div></td>
		</tr>
<? } ?>
		<tr>
			<td><div class="form-group"><?=$this->form->Register?></div></td>
		</tr>
	</table>
</form>

