<form id="<?=$this->form->getId()?>" name="<?=$this->form->getName()?>" enctype="<?=$this->form->getEnctype()?>" action="<?=$this->form->getAction()?>" method="<?=$this->form->getMethod()?>">
	<legend>Enter verify key</legend>
	<table>
		<tr>
			<td><div class="form-group"><?=$this->form->code?><?=$this->form->id?></div></td>
		</tr>
		<tr>
			<td><div class="form-group"><?=$this->form->Verify?></div></td>
		</tr>
	</table>
</form>

